# Staging overrides for nha-monitoring
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 14d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            resources:
              requests:
                storage: 20Gi
  grafana:
    persistence:
      size: 10Gi

loki-stack:
  loki:
    persistence:
      enabled: false
    config:
      storage_config:
        aws:
          s3: "s3://us-east-1/easyshop-staging-logs-bucket"
